terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file '/home/shashank/bgu-upf-map/Exp-Set-2/maze-2/icaps18/result-aij/domain-maze.pddl'
